### ISSUE TITLE
상품 댓글에서 보낸 사람이 뜨지 않는 문제

### ISSUE THREAD

**Issue by DPRLive** [DPRLive/MetaAuction#10]
![image](https://github.com/DPRLive/MetaAuction/assets/64268750/3c6d1463-4d99-48eb-8cd8-156f0f803f4e)
사진과 같습니다. (사진은 1번 물품)

**Comment by MistarJo** [comment]
<img width="262" alt="image" src="https://github.com/DPRLive/MetaAuction/assets/51068131/a1e7a4af-78ef-4c4e-9aa9-3e9b0e6f9a7e">

고쳤습니다
