### ISSUE TITLE
1대1 채팅에 보낸 사람이 뜨지 않는 문제

### ISSUE THREAD

**Issue by DPRLive** [DPRLive/MetaAuction#11]
![image](https://github.com/DPRLive/MetaAuction/assets/64268750/8939382b-74c5-4f5d-bf13-24dad58f5d8d)

String, UKnown Error 는 에러가 아니고 메세지 내용입니다. (종훈이가 장난쳤음ㅎㅎ;)

사진과 같이 보낸사람이 뜨지 않습니다.
+ 보낸 시간 추가 부탁드립니다.

**Comment by DPRLive** [comment]
내가 보낸 채팅도 동그랗게 감싸주시면 좋을 것 같기는 한데요..

**Comment by MistarJo** [comment]
수정 완료

**Comment by MistarJo** [comment]
수정 완료
