### ISSUE TITLE
아이템 모델 보기 이후 Input 문제

### ISSUE THREAD

**Issue by DPRLive** [DPRLive/MetaAuction#13]
(버그 재현 순서)
F 눌러서 상호 작용 -> 자세히 -> X 버튼 -> 아이템 상세보기 창이 떠있는데  Input Mode가 바로 Game으로 변경됨

**Comment by DPRLive** [comment]
F 눌러서 상호 작용 -> 자세히 -> transform 변경 위젯 -> 어떠한 이유로든 닫힌 뒤 
같은 문제가 발생합니다.

**Comment by MistarJo** [comment]
transform 변경 위젯이 닫히고 문제가 발생하나요?

**Comment by DPRLive** [comment]
닫히는 경우 (변경 버튼, 취소버튼, x버튼) 모두 문제가 발생합니다.
