### ISSUE TITLE
입찰 버튼 두번 누를 시 입찰이 되지 않는 문제

### ISSUE THREAD

**Issue by DPRLive** [DPRLive/MetaAuction#16]
![image](https://github.com/DPRLive/MetaAuction/assets/64268750/bd56c141-94f4-4384-ba41-711b1b9767b7)
버그 재현 : 가격을 따로 설정하지 않고 입찰 -> 성공 -> 한번 더(가격이 좀 더 높게 설정되어 있음) -> 낮은 가격이라고 안내가 뜸

**Comment by DPRLive** [comment]
가격 사이에 , 이 있어서 파싱이 잘 되지 않는것 같기도 합니다

**Comment by MistarJo** [comment]
코드 깜박하고 빼먹었네요...
',' 때문에 맞습니다.

```
// 빼먹은 부분
// ThisPtr->BidPriceText->SetText(FText::AsNumber(Price + ThisPtr->BidMinimum));

// 수정
ThisPtr->BidPriceText->SetText(FText::AsNumber(Price + ThisPtr->BidMinimum, &NumberFormatOptions));
```
